import { Student } from "./Student"

export const STUDENTS: Student[] = [
    {name:'Anna', surname: 'Smith', id:1},
    {name:'John', surname: 'Doe', id:2},
    {name:'Fran', surname: 'Podolski', id:3},
    {name:'Mary', surname: 'Poppins', id:4},
    {name:'Petar', surname: 'Pan', id:5},
    {name:'Ivo', surname: 'Grgurević', id:6},
    {name:'Kristian', surname: 'Madžarević', id:7},
    {name:'SomeName', surname: 'SomeSurname', id:8},
    {name:'Ime', surname: 'Prezime', id:9},
    {name:'Ivan', surname: 'Tomić', id:10},
    {name:'Anna', surname: 'Smith', id:11},
    {name:'John', surname: 'Doe', id:12},
    {name:'Fran', surname: 'Podolski', id:13},
    {name:'Mary', surname: 'Poppins', id:14},
    {name:'Petar', surname: 'Pan', id:15},
    {name:'Ivo', surname: 'Grgurević', id:16},
    {name:'Kristian', surname: 'Madžarević', id:17},
    {name:'SomeName', surname: 'SomeSurname', id:18},
    {name:'Ime', surname: 'Prezime', id:19},
    {name:'Ivan', surname: 'Tomić', id:20},
    {name:'Anna', surname: 'Smith', id:21},
    {name:'John', surname: 'Doe', id:22},
    {name:'Fran', surname: 'Podolski', id:23},
    {name:'Mary', surname: 'Poppins', id:24},
    {name:'Petar', surname: 'Pan', id:25},
    {name:'Ivo', surname: 'Grgurević', id:26},
    {name:'Kristian', surname: 'Madžarević', id:27},
    {name:'SomeName', surname: 'SomeSurname', id:28},
    {name:'Ime', surname: 'Prezime', id:29},
    
];