import { Student } from "./Student";

export const STUDENTS: Student[] = [
    {name:'Anna', surname: 'Smith', id:1, position:'None', assigned:false, toAssign:false},
    {name:'John', surname: 'Doe', id:2, position:'None', assigned:false, toAssign:false},
    {name:'Fran', surname: 'Podolski', id:3, position:'None', assigned:false, toAssign:false},
    {name:'Mary', surname: 'Poppins', id:4, position:'None', assigned:false, toAssign:false},
    {name:'Petar', surname: 'Pan', id:5, position:'None', assigned:false, toAssign:false},
    {name:'Ivo', surname: 'Grgurević', id:6, position:'None', assigned:false, toAssign:false},
    {name:'Kristian', surname: 'Madžarević', id:7, position:'None', assigned:false, toAssign:false},
    {name:'SomeName', surname: 'SomeSurname', id:8, position:'None', assigned:false, toAssign:false},
    {name:'Ime', surname: 'Prezime', id:9, position:'None', assigned:false, toAssign:false},
    {name:'Ivan', surname: 'Tomić', id:10, position:'None', assigned:false, toAssign:false},
    {name:'Anna', surname: 'Smith', id:11, position:'None', assigned:false, toAssign:false},
    {name:'John', surname: 'Doe', id:12, position:'None', assigned:false, toAssign:false},
    {name:'Fran', surname: 'Podolski', id:13, position:'None', assigned:false, toAssign:false},
    {name:'Mary', surname: 'Poppins', id:14, position:'None', assigned:false, toAssign:false},
    {name:'Petar', surname: 'Pan', id:15, position:'None', assigned:false, toAssign:false},
    {name:'Ivo', surname: 'Grgurević', id:16, position:'None', assigned:false, toAssign:false},
    {name:'Kristian', surname: 'Madžarević', id:17, position:'None', assigned:false, toAssign:false},
    {name:'SomeName', surname: 'SomeSurname', id:18, position:'None', assigned:false, toAssign:false},
    {name:'Ime', surname: 'Prezime', id:19, position:'None', assigned:false, toAssign:false},
    {name:'Ivan', surname: 'Tomić', id:20, position:'None', assigned:false, toAssign:false},
    {name:'Anna', surname: 'Smith', id:21, position:'None', assigned:false, toAssign:false},
    {name:'John', surname: 'Doe', id:22, position:'None', assigned:false, toAssign:false},
    {name:'Fran', surname: 'Podolski', id:23, position:'None', assigned:false, toAssign:false},
    {name:'Mary', surname: 'Poppins', id:24, position:'None', assigned:false, toAssign:false},
    {name:'Petar', surname: 'Pan', id:25, position:'None', assigned:false, toAssign:false},
    {name:'Ivo', surname: 'Grgurević', id:26, position:'None', assigned:false, toAssign:false},
    {name:'Kristian', surname: 'Madžarević', id:27, position:'None', assigned:false, toAssign:false},
    {name:'SomeName', surname: 'SomeSurname', id:28, position:'None', assigned:false, toAssign:false},
    {name:'Ime', surname: 'Prezime', id:29, position:'None', assigned:false, toAssign:false},
];